services:
  course-srv:
    image: imashiksarkar/course-lms:v1.0.0
    env_file:
      - ./course/.env.dev
    networks:
      - lms

  order-srv:
    image: imashiksarkar/order-lms:v1.0.0
    env_file:
      - ./order/.env.dev
    networks:
      - lms

  nginx:
    image: nginx:mainline-alpine3.23-slim
    ports:
      - '8080:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - course-srv
      - order-srv
    networks:
      - lms

networks:
  lms:
    driver: bridge
