services:
  course-srv:
    image: imashiksarkar/course-lms:v1.0.1
    env_file:
      - ./course/.env.dev

  order-srv:
    image: imashiksarkar/order-lms:v1.0.1
    env_file:
      - ./order/.env.dev

  nginx-srv:
    image: nginx:mainline-alpine3.23-slim
    ports:
      - '8080:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - course-srv
      - order-srv